# Generated by Django 5.2.6 on 2025-09-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('origin', models.CharField(max_length=100)),
                ('engine', models.CharField(blank=True, max_length=100, null=True)),
                ('horsepower', models.IntegerField(blank=True, null=True)),
                ('top_speed', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
